### ISSUE TITLE
생각할 거리들 여기에 정리 

### ISSUE THREAD

**Issue by jangchulwoon** [jangchulwoon/TIL#1]

**Comment by JangChulwoon** [comment]
![image](https://user-images.githubusercontent.com/12491632/42792331-b01ce67e-89af-11e8-9e71-e78f22af0690.png)

mockito 에서 private method를 지원하지 않는 이유

**Comment by JangChulwoon** [comment]
https://github.com/mockito/mockito/wiki/Mockito-And-Private-Methods

**Comment by JangChulwoon** [comment]
control + shift + J  문자열 join 

"dkssud" +
"hell"

=> 
"dkssudhell" 

---

control + shift  + 방향키 

문법적 오류가 없는 선에서 이동이 된다.

---


control alt shift 	방향키
element 들의 위치를 바꿀수잇다.
(HTML 이나 XML 상에서 ... )

---

메서드 인자 확인  
() 안에서 control+P 를 누르면 인자 및 인자 이름을 알 수 있음 

--

 라이브러리 보면 

ctr  + p  
를 쓰면 Document를 볼 수 있음


---

메서드 구현부 보기

control shift i  

메서드의 구현부를 볼 수 있음

인스턴스에 사용하면
어떻게 초기화 되었는지도 알 수 있음
(짱인데 ?)

class에 쓰면 클래스의 전체 코드가 나옴 ..;; 
굿 ..

js 도 가능한거 같은데 .. ? 올
